name: Manual Build

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - 'rs_lambda_*'  # Adjust this pattern to match your rc_ branch naming convention
  
jobs: 
  branch_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: branch_check
        run: |
          branch_name="${{ github.ref_name }}"
          if [[ ! "$branch_name" =~ ^refs/heads/rc_ ]]; then
            echo "Branch name '$branch_name' does not match the expected pattern (rc_)."
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This permission is required for requesting the web token without which you can't access the aws 
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: LOGIN TO AWS Account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::121212121212:role/CodeBuildFromGitHub
          aws-region: us-east-1

      - name: Run Build
        id: start-build
        run: |
          # Get build id from json output generated by the aws command 
          BUILD_ID=$(aws codebuild start-build --project mimas-build --source-version $GITHUB_SHA | jq -r '.build.id')
          
          # set an output variable BUILD_ID that can be used in subsequent steps
          echo "::set-output name=build-id::$BUILD_ID"

          # Wait for the build to complete
          while true; do

            # Getting current status and phases of the build
            BUILD_STATUS=$(aws codebuild batch-get-builds --ids $BUILD_ID | jq -r '.builds[0].buildStatus')
            BUILD_PHASE=$(aws codebuild batch-get-builds --ids $BUILD_ID | jq -r '.builds[0].currentPhase')
            echo "Current build status: $BUILD_STATUS"
            echo "Current build phase: $BUILD_PHASE"

            if [[ "$BUILD_STATUS" == "SUCCEEDED" ]]; then
              break
            elif [[ "$BUILD_STATUS" == "FAILED" ]]; then
              echo "Build failed"
              exit 1
            fi

            sleep 45
          done
