name: Build check for RC merge

on:
  pull_request:
    branches:
      - 'rs_'  # Adjust this pattern to match your rc_ branch naming convention
  


jobs:
  check-latest-commit-message:
    name: 'Get commit message'
    runs-on: ubuntu-latest
    permissions:
      # this permission should be set to be able use secrets.GITHUB_TOKEN
      id-token: write
      # not sure if this permission is necessary, just didn't try to remove it when testing
      contents: read
      # this permission should be set to be able get commits data by curl request
      pull-requests: read
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        run: |
          echo "$(git show -s --format=%s)" 
