name: Build check for RC merge

on:
  pull_request:
    branches:
      - 'rs_'  # Adjust this pattern to match your rc_ branch naming convention
  


jobs:
  check-latest-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get List of Commit SHAs
        id: commit-list
        run: |
          # Get a list of commit SHAs excluding merge commits
          COMMIT_LIST=$(git log --merges --invert-grep --pretty=format:%H..origin/main)
          
          # Save the commit list to an environment file
          echo "COMMIT_LIST=${COMMIT_LIST}" >> $GITHUB_ENV

      - name: Check Latest Commit Message
        run: |
          # Retrieve the list of commit SHAs from the environment file
          COMMIT_LIST="${COMMIT_LIST}"

          # Loop through the commit messages and check if any contain 'CodeBuild'
          for commit_sha in $COMMIT_LIST; do
            COMMIT_MESSAGE=$(git log -1 --pretty=format:%s $commit_sha)
            echo "Commit message: $COMMIT_MESSAGE"

            if [[ "$COMMIT_MESSAGE" =~ "CodeBuild" ]]; then
              echo "Commit message contains 'CodeBuild'. Proceeding with workflow."
              # Add your workflow steps here
              exit 0
            fi
          done

          # If no matching commit messages were found, skip the workflow
          echo "None of the commit messages contain 'CodeBuild'. Skipping workflow."
          exit 1  # Terminate the workflow with a non-zero status code
