name: Build check for RC merge

on:
  pull_request:
    branches:
      - 'rs_lambda_*'  # Adjust this pattern to match your rc_ branch naming convention
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This permission is required for requesting the web token without which you can't access the aws 
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      

      