name: Build check for RC merge

on:
  pull_request:
    branches:
      - 'rs_'  # Adjust this pattern to match your rc_ branch naming convention
  


jobs:
  check-latest-commit-message:
    name: 'Get commit message'
    runs-on: ubuntu-latest
    permissions:
      # this permission should be set to be able use secrets.GITHUB_TOKEN
      id-token: write
      # not sure if this permission is necessary, just didn't try to remove it when testing
      contents: read
      # this permission should be set to be able get commits data by curl request
      pull-requests: read
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checking head git commit message
        run: |
          echo "$(git show -s --format=%s)" 
          # Run the git show command and capture its output in an environment variable
          COMMIT_MESSAGE="$(git show -s --format=%s)"
  
          # Set the environment variable
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_EN
          
          # Check if the commit message starts with "CodeBuild"
          if [[ "$COMMIT_MESSAGE" == CodeBuild* ]]; then
            echo "Commit message starts with 'CodeBuild'. Proceeding with workflow."
            # Add your workflow steps here
          elif [[ "$COMMIT_MESSAGE" == *CodeBuild ]]; then
            echo "Commit message ends with 'CodeBuild'. Proceeding with workflow."
            # Add your workflow steps here
          else
            echo "Commit message does not start or end with 'CodeBuild'. Exiting workflow."
            exit 1  # Terminate the workflow with a non-zero status code
          fi
