name: Build check for RC merge

on:
  pull_request:
    branches:
      - 'rs_'  # Adjust this pattern to match your rc_ branch naming convention
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This permission is required for requesting the web token without which you can't access the aws 
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up jq
        run: |
          sudo apt-get update
          sudo apt-get install jq -y
      - name: Check Commit Messages
        run: |
          COMMITS_URL=$(jq -r '.pull_request.commits_url' <<< ${{ toJson(github.event) }})
          COMMIT_MESSAGES=()

          # Get commit messages for all commits associated with the pull request
          for commit_url in $(curl -s "$COMMITS_URL" | jq -r '.[].url'); do
            COMMIT_MESSAGE=$(curl -s "$commit_url" | jq -r '.commit.message')
            COMMIT_MESSAGES+=("$COMMIT_MESSAGE")
          done

          # Get the latest commit message (the last element in the array)
          LATEST_COMMIT_MESSAGE="${COMMIT_MESSAGES[-1]}"
          echo "Latest commit message: $LATEST_COMMIT_MESSAGE"
          
          # Use a regular expression to check for patterns
          if [[ "$commit_messages" =~ (^CodeBuild|CodeBuild$) ]]; then
            echo "Commit message matches the pattern. Proceeding with workflow."
            # Add your workflow steps here
          else
            echo "Commit message does not match the pattern. Skipping workflow."
            exit 1  # Terminate the workflow with a non-zero status code
          fi
      - name: testing 
        run: |
              echo "Testing"
            
       
    

      
