name: Build check for RC merge

on:
  pull_request:
    branches:
      - 'rs_'  # Adjust this pattern to match your rc_ branch naming convention
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This permission is required for requesting the web token without which you can't access the aws 
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Commit Messages
        run: |
          # Use Git commands to access and check commit messages
          #commit_messages=$(git log --format=%B origin/main..HEAD)
          LATEST_COMMIT_MESSAGE="${{ github.event.pull_request.head.commit.message }}"
          echo "Latest commit message: $LATEST_COMMIT_MESSAGE"
          
          # Use a regular expression to check for patterns
          if [[ "$commit_messages" =~ (^CodeBuild|CodeBuild$) ]]; then
            echo "Commit message matches the pattern. Proceeding with workflow."
            # Add your workflow steps here
          else
            echo "Commit message does not match the pattern. Skipping workflow."
            exit 1  # Terminate the workflow with a non-zero status code
          fi
      - name: testing 
        run: |
              echo "Testing"
            
       
    

      
